### ISSUE TITLE
User can view the products for sale.

### ISSUE THREAD

**Issue by tonykjin** [tonykjin/shopping-cart#2]
### Task List

- [x] Define a stateful `App` component in `client/components/app.jsx` with an initial state that includes an empty `Array` of products.
- [x] Define a stateless `Header` component in `client/components/header.jsx` that displays the store's name and logo. Add `Header` to `App`'s render method.
- [x] Define a method in `App` named `getProducts` that retrieves all products by sending a `GET` request to `/api/products.php`.
- [x] Add a `componentDidMount` method to `App` that calls `getProducts`.
- [x] Define a stateless `ProductListItem` component in `client/components/product-list-item.jsx` that renders a single product card.
- [x] Define a stateless `ProductList` component in `client/components/product-list.jsx` that renders a grid of `ProductListItems`.
- [x] Add `ProductList` to `App`'s render method and pass it all of `App`'s products as a prop.
